import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { describe, expect, it } from "vitest";

const here = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(here, "../..");
const specPath = path.resolve(packageRoot, "../../apps/api/src/openapi.yaml");
const committedPath = path.resolve(packageRoot, "src/generated/types.ts");

// The mirrored public repo (github.com/peppol-sh/peppol-sh-ts) ships the
// vendored types without the OpenAPI spec beside them, so there is nothing to
// compare against there. In the monorepo the spec is present and the committed
// types must match it exactly.
const describeInMonorepo = existsSync(specPath) ? describe : describe.skip;

// The banner the openapi-typescript CLI prepends; the node API does not.
const BANNER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

describeInMonorepo("generated types", () => {
  it("match apps/api/src/openapi.yaml", async () => {
    const regenerated = astToString(
      await openapiTS(new URL(`file://${specPath}`)),
    );

    expect(
      readFileSync(committedPath, "utf-8"),
      "src/generated/types.ts is stale — run `bun run generate:types` in packages/sdk-typescript",
    ).toBe(BANNER + regenerated);
  });
});
